Logout section and revocation clarifications
italia/spid-cie-oidc-docs pull request #131
Opened 2022-12-16 11:26 UTC by fmarino-ipzs

## Title
Logout e revoca dei token
## Content
- Aggiunta la sezione di Logout
- Chiarimenti nella sezione di revocation

Closes #101 

## Review

- [ ] Ensure your files are written following RST specs (*not MD!*)
- [x] Italian version
- [x] English version
- [ ] Example files 
- [ ] Ask for review

2022-12-20 14:38 UTC, peppelinux requested changes

2022-12-20 14:38 UTC, peppelinux commented on docs/en/logout.rst
> +During the logout phase the RPs MUST revoke all Access Tokens still active and related to user authentication, through the use of the revocation endpoint ( :ref:`Revocation Endpoint <Revocation_Endpo
all *the* Access Tokens

2022-12-20 14:38 UTC, peppelinux commented on docs/en/revocation_endpoint.rst
> +The OP MUST to revoke the token specified in the request.
MUST revoke

2022-12-20 14:38 UTC, peppelinux commented on docs/it/logout.rst
> +I RP POSSONO instaurare sessioni individuali relative agli utenti autenticati. Nei casi in cui tali sessioni individuali vengano instaurate dai RP, questi utlimi DEVONO fornire agli utenti una funzio
utlimi -> ultimi

2022-12-20 15:24 UTC, fmarino-ipzs commented on docs/en/logout.rst
> +During the logout phase the RPs MUST revoke all Access Tokens still active and related to user authentication, through the use of the revocation endpoint ( :ref:`Revocation Endpoint <Revocation_Endpo
done

2022-12-20 15:24 UTC, fmarino-ipzs commented on docs/en/revocation_endpoint.rst
> +The OP MUST to revoke the token specified in the request.
Done

2022-12-20 15:24 UTC, fmarino-ipzs commented on docs/it/logout.rst
> +I RP POSSONO instaurare sessioni individuali relative agli utenti autenticati. Nei casi in cui tali sessioni individuali vengano instaurate dai RP, questi utlimi DEVONO fornire agli utenti una funzio
Done

2022-12-23 14:47 UTC, peppelinux requested changes

2022-12-23 14:47 UTC, peppelinux commented on docs/en/logout.rst
> +During the logout phase the RPs MUST revoke all the Access Tokens still active and related to user authentication, through the use of the revocation endpoint ( :ref:`Revocation Endpoint <Revocation_E
attenzione, nella PR di @damikael al logout locale sull'RP devono essere revocati sia AT che eventuali refresh token

2022-12-23 14:47 UTC, peppelinux commented on docs/en/revocation_endpoint.rst
> +The Access Token revocation MUST NOT imply revoking all the Refresh Tokens linked to it.
vedi mio commento precedente

2022-12-23 14:47 UTC, peppelinux commented on docs/it/logout.rst
> +Durante la fase di logout i RP DEVONO revocare tutti gli Access Token ancora attivi e collegati all'autenticazione degli utenti, tramite l'utilizzo del revocation endpoint (:ref:`Revocation Endpoint
vedi mio commento precedente

2022-12-23 14:47 UTC, peppelinux commented on docs/it/revocation_endpoint.rst
> +La revoca di un Access Token NON DEVE comportare la revoca di tutti i Refresh Token a questo collegati.
vedi mio commento precedente

2022-12-27 15:35 UTC, fmarino-ipzs commented
I contenuti di questa PR sono stati inseriti nella PR #144

2022-12-27 15:35 UTC, closed without merging