fix: scope in the access token
italia/spid-cie-oidc-docs pull request #132
Opened 2022-12-16 18:23 UTC by fmarino-ipzs

## Title
Parametro scope nell'Access Token
## Content
Aggiunto il parametro scope nell'Access Token

closes #125 

## Review

- [ ] Ensure your files are written following RST specs (*not MD!*)
- [x] Italian version
- [x] English version
- [ ] Example files 
- [ ] Ask for review

2022-12-22 09:54 UTC, agcolella approved these changes

2022-12-22 09:54 UTC, damikael approved these changes

2022-12-22 09:54 UTC, nunzionapoli approved these changes

2022-12-23 14:45 UTC, peppelinux requested changes

2022-12-23 14:45 UTC, peppelinux commented on docs/en/token_endpoint.rst
> +   * - **scope**
@fmarino-ipzs possiamo citare l'RFC o la BCP che indica il parametro scope come SHOULD o MUST?

2022-12-23 14:45 UTC, peppelinux commented on docs/it/token_endpoint.rst
> +     - DEVE coincidere con il valore presente in fase di richiesta di autenticazione.
vedi mio commento precedente

2022-12-27 15:35 UTC, fmarino-ipzs commented
I contenuti di questa PR sono stati inseriti nella PR #144

2022-12-27 15:35 UTC, closed without merging